# Generated by Django 4.2 on 2023-04-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_genre_publisher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publisher',
            unique_together={('name', 'country')},
        ),
    ]
