# Generated by Django 4.2 on 2023-04-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_publisher_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
